# Generated by Django 5.0.6 on 2024-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register', 'verbose_name_plural': 'Register'},
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='isaaba82@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
